default:
  image: nrel/openstudio:3.2.1

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/os-measures

before_script:
  - bundle install
  
test:
  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - echo 'Configuring test environment'
  - source ./env.sh && download_gems
  - echo 'Copying gems to standard location for our containers'
  - mkdir -p /var/gems
  - cp -r ../.gems/* /var/gems
  - echo 'Copying additional data to openstudio-standards'
  - cp -f openstudio-server/ServerData/weather/CAN_* /var/gems/openstudio-standards/data/weather
  - echo 'Starting tests'
  - cd test
  - bundle exec ruby test_measures.rb
  
  cache:
    key: "OSmeasures"
    paths:
      - vendor/bundle

