default:
  image: nrel/openstudio:3.2.1

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/os-measures

test_README:
  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - |
    echo 'Measures are tested on three seperate images. They should pass on all.'
    echo '  The test_using_nrel_image and test_using_nrc_image tests should match the configuration'
    echo '    in the local testing environment.'
    echo '  The test_using_nrel_server_image image is used by PAT. The modifications in'
    echo '    this test should be identical to those in the NRC server configuration scripts.'

test_using_nrel_image:
  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - echo 'Configuring test environment using NREL openstudio'
  - echo '  This image can be used in testing'
  - source ./env.sh && download_gems
  - echo 'Copying gems to standard location for our containers'
  - mkdir -p /var/gems
  - cp -r ../.gems/* /var/gems
  - echo 'Copying additional data to openstudio-standards'
  - cp -fr openstudio-server/ServerData/weather /var/gems/openstudio-standards/data
  - echo 'Starting tests'
  - cd test
  - bundle install
  - bundle exec ruby test_measures.rb
  
  cache:
    key: "OSmeasures"
    paths:
      - vendor/bundle

test_using_nrc_image:
  image: localhost:5000/nrc_openstudio:3.2.1.a

  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - echo 'Configuring test environment using NRC specific openstudio'
  - echo '  This image can be used in testing'
  - echo 'Starting tests'
  - cd test
  - bundle install
  - bundle exec ruby test_measures.rb
  
  cache:
    key: "OSmeasures"
    paths:
      - vendor/bundle

test_using_nrel_server_image:
  image: nrel/openstudio-server:3.2.1

  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - echo 'Configuring test environment using openstudio-server'
  - echo '  This is the image used by PAT'
  - source ./env.sh && download_gems
  - echo 'Copying gems to standard location for our containers'
  - mkdir -p /var/gems
  - cp -r ../.gems/* /var/gems
  - echo 'Copying additional data to openstudio-standards'
  - cp -fr openstudio-server/ServerData/weather /var/gems/openstudio-standards/data
  - echo 'Starting tests'
  - cd test
  - bundle install
  - bundle exec ruby test_measures.rb
  
  cache:
    key: "OSmeasures"
    paths:
      - vendor/bundle

