

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/os-measures

README:
  stage: build
  tags:
  - linux
  - docker
  - const-ibp
  
  script:
  - |
    echo 'Measures are tested on three seperate images. They should pass on all.'
    echo '  The test_using_nrel_image and test_using_nrc_image tests should match the configuration'
    echo '    in the local testing environment.'
    echo '  The test_using_nrel_server_image image is used by PAT. The modifications in'
    echo '    this test should be identical to those in the NRC server configuration scripts.'

using_nrel_image:
  stage: test 
  image: nrel/openstudio:3.2.1

  tags:
  - linux
  - docker
  - const-ibp
  
  before_script:
  - echo 'Configuring test environment using NREL openstudio'
  - echo '  This image can be used in testing'
  - cd test
  - source ../env.sh && download_gems
  - echo 'Copying gems to standard location for our containers'
  - mkdir -p /var/gems
  - cp -r ../.gems/* /var/gems
  - echo 'Copying additional data to openstudio-standards'
  - cp -fr ../openstudio-server/ServerData/weather /var/gems/openstudio-standards/data
  - bundle install

  script:
  - echo 'Starting tests'
  - bundle exec ruby test_measures.rb

test_using_nrc_image:
  stage: test
  image: localhost:5000/openstudio

  tags:
  - linux
  - docker
  - const-ibp
  
  before_script:
  - echo 'Configuring test environment using NRC specific openstudio'
  - echo '  This image can be used in testing'
  - cd test
  - bundle install
  - ls /var/gems/openstudio-standards/data/weather/CAN*epw

  script:
  - echo 'Starting tests'
  - bundle exec ruby test_measures.rb

using_nrel_server_image:
  stage: test
  image: nrel/openstudio-server:3.2.1

  tags:
  - linux
  - docker
  - const-ibp
  
  before_script:
  - echo 'Configuring test environment using openstudio-server'
  - echo '  This is the image used by PAT'
  - cd test
  - source ../env.sh && download_gems
  - echo 'Copying gems to standard location for our containers'
  - mkdir -p /var/gems
  - cp -r ../.gems/* /var/gems
  - echo 'Copying additional data to openstudio-standards'
  - cp -fr ../openstudio-server/ServerData/weather /var/gems/openstudio-standards/data
  - bundle install

  script:
  - echo 'Starting tests'
  - bundle exec ruby test_measures.rb
