# Test dockerfile

# Build NRC specific version of openstudio container for testing our measures.
FROM nrel/{os_image} as base

# Set the environment variables that we require.
ENV RUBYLIB={gemDir}:$RUBYLIB

# Set the timezone.
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -qq && \
    echo "tzdata tzdata/Areas select America" | debconf-set-selections && \
    echo "tzdata tzdata/Zones/America select Toronto" | debconf-set-selections; # && \
    apt-get install -y tzdata && \
    dpkg-reconfigure tzdata;

# Install R (from https://mirror.rcg.sfu.ca/mirror/CRAN/).
RUN apt install -y software-properties-common dirmngr wget && \
    wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc && \
    add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/" && \
    apt-get install -y r-base ;

# Install the R packages that we use the most.
RUN Rscript -e 'install.packages("tidyverse", repos="https://cloud.r-project.org")'
